adapters = ["crates.io"]

[[package]]
name = "opentf-release"
adapter = "crates.io"
mode = "build-only"
matrix = true
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
command = "cargo build --release -p opentf-release --target ${{ matrix.target }}"
artifacts = "target/${{ matrix.target }}/release/otf-release*"
